<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Package dependencies -->
    <PackageVersion Include="EA" Version="1.1.17100" />
    <PackageVersion Include="Fp.Plus" Version="0.29.0" />
    <PackageVersion Include="OpenTK.Audio.OpenAL" Version="4.9.4" />
    <PackageVersion Include="System.CommandLine" Version="2.0.5" />
    <!-- Test dependencies -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageVersion Include="coverlet.collector" Version="8.0.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
